# Generated by Django 5.2.7 on 2025-11-04 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Article title', max_length=200)),
                ('slug', models.SlugField(help_text='URL-friendly version of title', max_length=200, unique=True)),
                ('article_type', models.CharField(choices=[('essay', 'Essay'), ('visual_essay', 'Visual Essay'), ('data_essay', 'Data Essay'), ('tutorial', 'Tutorial'), ('case_study', 'Case Study')], default='essay', max_length=20)),
                ('excerpt', models.TextField(help_text='Short description for listing pages', max_length=500)),
                ('content', models.TextField(help_text='Main article content (supports HTML)')),
                ('featured_image', models.ImageField(blank=True, help_text='Main image shown at top of article', null=True, upload_to='articles/images/')),
                ('image_caption', models.CharField(blank=True, max_length=200)),
                ('has_interactive_content', models.BooleanField(default=False, help_text='Check if article includes charts, graphs, or interactive elements')),
                ('custom_css', models.TextField(blank=True, help_text='Custom CSS for this article (optional)')),
                ('custom_javascript', models.TextField(blank=True, help_text='Custom JavaScript for interactive content (optional)')),
                ('tags', models.JSONField(blank=True, default=list, help_text='Tags as list, e.g., ["product", "design", "AI"]')),
                ('read_time', models.IntegerField(default=5, help_text='Estimated reading time in minutes')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('archived', 'Archived')], default='draft', max_length=20)),
                ('published_date', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('meta_description', models.CharField(blank=True, help_text='SEO meta description (150-160 chars)', max_length=160)),
                ('is_featured', models.BooleanField(default=False, help_text='Show in featured section on home page')),
            ],
            options={
                'verbose_name': 'Article/Essay',
                'verbose_name_plural': 'Articles/Essays',
                'ordering': ['-published_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='GalleryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('image', models.ImageField(upload_to='gallery/')),
                ('thumbnail', models.ImageField(blank=True, help_text='Optional thumbnail (will use main image if not provided)', null=True, upload_to='gallery/thumbnails/')),
                ('gallery_type', models.CharField(choices=[('photo', 'Photography'), ('design', 'Design Work'), ('art', 'Art'), ('project', 'Project Screenshot'), ('other', 'Other')], default='photo', max_length=20)),
                ('tags', models.JSONField(blank=True, default=list)),
                ('external_link', models.URLField(blank=True)),
                ('order', models.IntegerField(default=0)),
                ('is_visible', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Gallery Item',
                'verbose_name_plural': 'Gallery Items',
                'ordering': ['order', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RecentActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_type', models.CharField(choices=[('article', 'Published Article'), ('project', 'Shipped Project'), ('talk', 'Gave Talk'), ('achievement', 'Achievement'), ('learning', 'Learning'), ('other', 'Other')], max_length=20)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('link', models.URLField(blank=True, help_text='Link to article, project, etc.')),
                ('date', models.DateField()),
                ('order', models.IntegerField(default=0)),
                ('is_visible', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Recent Activity',
                'verbose_name_plural': 'Recent Activities',
                'ordering': ['-date', 'order'],
            },
        ),
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Ken Ruto - Resume', help_text='Title for the resume', max_length=200)),
                ('resume_file', models.FileField(help_text='Upload PDF resume', upload_to='resume/')),
                ('summary', models.TextField(blank=True, help_text='Professional summary')),
                ('is_active', models.BooleanField(default=True, help_text='Set as active resume (only one should be active)')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Resume/CV',
                'verbose_name_plural': 'Resumes/CVs',
            },
        ),
        migrations.AlterModelOptions(
            name='nowitem',
            options={'ordering': ['order'], 'verbose_name': "What I'm Doing Now", 'verbose_name_plural': "What I'm Doing Now Items"},
        ),
        migrations.AlterField(
            model_name='nowitem',
            name='icon',
            field=models.CharField(help_text='Emoji or icon name (e.g., 📚, 🚀, 🎬)', max_length=50),
        ),
        migrations.AlterField(
            model_name='skill',
            name='category',
            field=models.CharField(choices=[('product', 'Technical Product Management'), ('engineering', 'Engineering & Data'), ('leadership', 'Leadership'), ('design', 'Design & Creativity')], max_length=20),
        ),
    ]
